"use client";

import { useState, useCallback } from "react";

interface UniversalActionSuiteProps {
  content: string;
  toolName: string;
  toolUrl?: string;
}

export default function UniversalActionSuite({
  content,
  toolName,
  toolUrl,
}: UniversalActionSuiteProps) {
  const [copyStatus, setCopyStatus] = useState<"idle" | "copied" | "error">("idle");
  const [shareStatus, setShareStatus] = useState<"idle" | "shared" | "error">("idle");
  const [downloadStatus, setDownloadStatus] = useState<"idle" | "done">("idle");
  const [pdfStatus, setPdfStatus] = useState<"idle" | "generating" | "done" | "error">("idle");

  // ─── COPY TO CLIPBOARD ───────────────────────────────────
  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(content);
      setCopyStatus("copied");
      setTimeout(() => setCopyStatus("idle"), 2500);
    } catch {
      // Fallback for older browsers
      const el = document.createElement("textarea");
      el.value = content;
      el.style.position = "fixed";
      el.style.opacity = "0";
      document.body.appendChild(el);
      el.select();
      document.execCommand("copy");
      document.body.removeChild(el);
      setCopyStatus("copied");
      setTimeout(() => setCopyStatus("idle"), 2500);
    }
  }, [content]);

  // ─── SHARE LINK ─────────────────────────────────────────
  const handleShare = useCallback(async () => {
    const shareUrl = toolUrl || window.location.href;
    if (navigator.share) {
      try {
        await navigator.share({
          title: `${toolName} — ToolGlobe`,
          text: `Check out this free online tool: ${toolName}`,
          url: shareUrl,
        });
        setShareStatus("shared");
        setTimeout(() => setShareStatus("idle"), 2500);
      } catch {
        // User cancelled share
      }
    } else {
      try {
        await navigator.clipboard.writeText(shareUrl);
        setShareStatus("shared");
        setTimeout(() => setShareStatus("idle"), 2500);
      } catch {
        setShareStatus("error");
        setTimeout(() => setShareStatus("idle"), 2500);
      }
    }
  }, [toolName, toolUrl]);

  // ─── DOWNLOAD AS TXT ────────────────────────────────────
  const handleDownloadTxt = useCallback(() => {
    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${toolName.toLowerCase().replace(/\s+/g, "-")}-result.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setDownloadStatus("done");
    setTimeout(() => setDownloadStatus("idle"), 2500);
  }, [content, toolName]);

  // ─── EXPORT AS PDF ──────────────────────────────────────
  const handleExportPdf = useCallback(async () => {
    setPdfStatus("generating");
    try {
      // Dynamic import to avoid SSR issues
      const jsPDFModule = await import("jspdf");
      const jsPDF = jsPDFModule.default;
      const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 20;
      const maxWidth = pageWidth - 2 * margin;

      // Header
      doc.setFillColor(59, 130, 246);
      doc.rect(0, 0, pageWidth, 22, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("ToolGlobe — Free Online Tools", margin, 14);

      // Title
      doc.setTextColor(30, 41, 59);
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text(toolName, margin, 34);

      // Divider
      doc.setDrawColor(203, 213, 225);
      doc.line(margin, 38, pageWidth - margin, 38);

      // Content
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(71, 85, 105);

      const lines = doc.splitTextToSize(content, maxWidth);
      let y = 46;
      const lineHeight = 5;
      const pageHeight = doc.internal.pageSize.getHeight();

      for (const line of lines) {
        if (y + lineHeight > pageHeight - 20) {
          doc.addPage();
          y = 20;
        }
        doc.text(line, margin, y);
        y += lineHeight;
      }

      // Footer
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const totalPages = (doc.internal as any).getNumberOfPages() as number;
      for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(7);
        doc.setTextColor(148, 163, 184);
        doc.text(
          `Generated by ToolGlobe.app | Page ${i} of ${totalPages} | ${new Date().toLocaleDateString()}`,
          margin,
          pageHeight - 10
        );
        doc.text("toolglobe.app", pageWidth - margin - 20, pageHeight - 10);
      }

      doc.save(`${toolName.toLowerCase().replace(/\s+/g, "-")}-result.pdf`);
      setPdfStatus("done");
      setTimeout(() => setPdfStatus("idle"), 3000);
    } catch (err) {
      console.error("PDF generation error:", err);
      setPdfStatus("error");
      setTimeout(() => setPdfStatus("idle"), 3000);
    }
  }, [content, toolName]);

  const buttons = [
    {
      id: "copy",
      label: copyStatus === "copied" ? "Copied! ✓" : "Copy",
      icon: copyStatus === "copied" ? "✓" : "📋",
      onClick: handleCopy,
      disabled: !content,
      className:
        copyStatus === "copied"
          ? "bg-green-500 text-white border-green-500"
          : "bg-white text-slate-700 border-slate-200 hover:bg-blue-50 hover:border-blue-300 hover:text-blue-700",
    },
    {
      id: "share",
      label: shareStatus === "shared" ? "Link Copied! ✓" : "Share",
      icon: "🔗",
      onClick: handleShare,
      disabled: false,
      className:
        shareStatus === "shared"
          ? "bg-green-500 text-white border-green-500"
          : "bg-white text-slate-700 border-slate-200 hover:bg-purple-50 hover:border-purple-300 hover:text-purple-700",
    },
    {
      id: "download",
      label: downloadStatus === "done" ? "Downloaded! ✓" : "Download TXT",
      icon: "⬇️",
      onClick: handleDownloadTxt,
      disabled: !content,
      className:
        downloadStatus === "done"
          ? "bg-green-500 text-white border-green-500"
          : "bg-white text-slate-700 border-slate-200 hover:bg-teal-50 hover:border-teal-300 hover:text-teal-700",
    },
    {
      id: "pdf",
      label:
        pdfStatus === "generating"
          ? "Generating…"
          : pdfStatus === "done"
          ? "Exported! ✓"
          : pdfStatus === "error"
          ? "PDF Error"
          : "Export PDF",
      icon: "📄",
      onClick: handleExportPdf,
      disabled: !content || pdfStatus === "generating",
      className:
        pdfStatus === "done"
          ? "bg-green-500 text-white border-green-500"
          : pdfStatus === "error"
          ? "bg-red-500 text-white border-red-500"
          : "bg-white text-slate-700 border-slate-200 hover:bg-rose-50 hover:border-rose-300 hover:text-rose-700",
    },
  ];

  return (
    <div className="flex flex-wrap gap-2">
      {buttons.map((btn) => (
        <button
          key={btn.id}
          onClick={btn.onClick}
          disabled={btn.disabled}
          aria-label={btn.label}
          className={`
            inline-flex items-center gap-1.5 px-3 py-2 rounded-lg border text-sm font-medium
            transition-all duration-200 cursor-pointer
            disabled:opacity-40 disabled:cursor-not-allowed
            ${btn.className}
          `}
        >
          <span className="text-base leading-none">{btn.icon}</span>
          <span>{btn.label}</span>
        </button>
      ))}
    </div>
  );
}
